import { useState, useCallback, useEffect, useRef } from 'react';
import { useTranslation } from 'react-i18next';
import { useSearchParams, useLocation } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { AlertCircle, FileText } from 'lucide-react';
import { toast } from 'sonner';
import { reportAPI } from './api';
import REPORT_TYPES from './config';
import GeneratorCard from './components/GeneratorCard';
import KeywordTrendResult from './components/KeywordTrendResult';
import AuthorImpactResult from './components/AuthorImpactResult';
import JournalQualityResult from './components/JournalQualityResult';
import ReportHistoryTable from './components/ReportHistoryTable';

/* ═══════════════════════════════════════════════════════════════════════════
   Main Component
   ═══════════════════════════════════════════════════════════════════════════ */
export default function ReportsViewPage() {
  const { t } = useTranslation('reports');
  const [searchParams] = useSearchParams();
  const location = useLocation();
  const [loading, setLoading] = useState(null);
  const [error, setError] = useState(null);
  const [result, setResult] = useState(null);
  const [history, setHistory] = useState([]);
  const [historyLoading, setHistoryLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const autoGeneratedRef = useRef(false);

  /* ── Load history from BE on mount (fallback to empty if unavailable) ── */
  useEffect(() => {
    let cancelled = false;
    async function loadHistory() {
      try {
        const data = await reportAPI.getHistory(0, 20);
        if (!cancelled && data?.content) {
          // Map BE format to FE entry format
          const mapped = data.content.map((item) => ({
            _id: item.reportId,
            type: (item.reportType || '').toLowerCase().replace(/_/g, '-'),
            query: item.queryText,
            timestamp: new Date(item.createdAt).getTime(),
            status: item.status || 'ready',
            reportName: item.reportName,
            // data not included in list — fetched on-demand via regenerate
            data: null,
          }));
          setHistory(mapped);
        }
      } catch {
        // BE endpoint not available yet — start with empty history, no error shown
      } finally {
        if (!cancelled) setHistoryLoading(false);
      }
    }
    loadHistory();
    return () => { cancelled = true; };
  }, []);

  /* ── Generate report ── */
  const generateReport = useCallback(async (type, query, apiFn) => {
    setLoading(type);
    setError(null);
    setResult(null);
    try {
      const data = await apiFn(query);
      const reportData = data?.data || data;
      const entry = {
        type,
        query,
        timestamp: Date.now(),
        status: 'ready',
        data: reportData,
      };
      setResult(entry);

      // Try to persist to BE; fall back to local-only
      try {
        const saved = await reportAPI.saveReport({
          reportType: type.toUpperCase().replace(/-/g, '_'),
          queryText: query,
          reportName: reportData.reportTitle || `${type} report: ${query}`,
        });
        entry._id = saved.reportId;
      } catch {
        // BE not available — keep local-only
      }

      setHistory((prev) => [entry, ...prev].slice(0, 50));
      toast.success(t('toast.success') || 'Report generated successfully');
    } catch (err) {
      const msg = err?.response?.data?.message || err?.message || 'Failed to generate report';
      setError(msg);
      toast.error(t('toast.error') || msg);
    } finally {
      setLoading(null);
    }
  }, [t]);

  /* ── Auto-generate from query params (integration from Search pages) ── */
  useEffect(() => {
    // Parse search params from location to ensure fresh values on every navigation
    const params = new URLSearchParams(location.search);
    const type = params.get('type');
    const q = params.get('q');

    if (type && q && REPORT_TYPES[type] && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      const apiFn = reportAPI[REPORT_TYPES[type].apiFn];
      if (apiFn) {
        // Small delay to ensure component is fully mounted
        const timer = setTimeout(() => {
          generateReport(type, q, apiFn);
        }, 100);
        return () => clearTimeout(timer);
      }
    }
  }, [location.search, generateReport]);

  /* ── Save report (from result panel) ── */
  const handleSave = useCallback(async (reportData) => {
    setSaving(true);
    try {
      // Try BE save
      const type = result?.type || 'keyword-trend';
      const query = result?.query || '';
      const saved = await reportAPI.saveReport({
        reportType: type.toUpperCase().replace(/-/g, '_'),
        queryText: query,
        reportName: reportData.reportTitle || `${type} report: ${query}`,
      });
      // Update entry in history with BE id
      setHistory((prev) => prev.map((entry) => {
        if (entry.timestamp === result?.timestamp && !entry._id) {
          return { ...entry, _id: saved.reportId };
        }
        return entry;
      }));
      toast.success('Report saved to history');
    } catch {
      // BE not available — already in local history
      toast.success('Report saved locally');
    } finally {
      setSaving(false);
    }
  }, [result]);

  /* ── Delete from history ── */
  const handleDelete = useCallback(async (index) => {
    const entry = history[index];
    // Try BE delete first
    if (entry?._id) {
      try {
        await reportAPI.deleteReport(entry._id);
      } catch {
        // BE not available — continue with local delete
      }
    }
    setHistory((prev) => prev.filter((_, i) => i !== index));
    toast.success('Report removed from history');
  }, [history]);

  /* ── View from history ── */
  const handleView = useCallback(async (entry) => {
    // If we have cached data, show immediately
    if (entry.data) {
      setResult(entry);
      window.scrollTo({ top: 0, behavior: 'smooth' });
      return;
    }
    // Otherwise try to regenerate from BE
    if (entry._id) {
      try {
        setLoading(entry.type);
        const regenerated = await reportAPI.regenerateReport(entry._id);
        const fullEntry = {
          ...entry,
          data: regenerated,
          timestamp: entry.timestamp || Date.now(),
        };
        setResult(fullEntry);
        // Update cache in history
        setHistory((prev) => prev.map((h) => (h._id === entry._id ? fullEntry : h)));
      } catch {
        toast.error('Failed to load report data');
      } finally {
        setLoading(null);
      }
      window.scrollTo({ top: 0, behavior: 'smooth' });
      return;
    }
    // Fallback: show entry as-is (may have no data)
    setResult(entry);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }, []);

  /* ── Error Banner ── */
  const ErrorBanner = error && (
    <motion.div
      initial={{ opacity: 0, y: -8 }}
      animate={{ opacity: 1, y: 0 }}
      className="flex items-center gap-2 px-4 py-3 rounded-xl bg-red-500/5 border border-red-500/10 text-[11px] text-red-400/80"
    >
      <AlertCircle size={13} className="shrink-0" />
      <span>{error}</span>
      <button onClick={() => setError(null)} className="ml-auto text-red-400/50 hover:text-red-400">✕</button>
    </motion.div>
  );

  return (
    <div className="w-full h-full min-h-screen p-8 space-y-6 overflow-y-auto bg-transparent">
      {/* HEADER — compact stats strip, title is in TopBar */}
      <motion.div
        initial={{ opacity: 0, y: -8 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex flex-wrap items-center gap-3"
      >
        <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-[#DEDBC8]/5 border border-[#DEDBC8]/8">
          <FileText size={13} className="text-[#DEDBC8]" />
          <span className="text-xs font-bold text-[#DEDBC8]">3 Report Types</span>
        </div>
        <span className="text-[11px] text-gray-500">Generate analytics reports for journals, authors, or topics</span>
      </motion.div>

      {/* Error Banner */}
      {ErrorBanner}

      {/* 3 REPORT GENERATOR CARDS */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
        <GeneratorCard
          icon={REPORT_TYPES['keyword-trend'].icon}
          iconColor={REPORT_TYPES['keyword-trend'].color}
          title={t('templates.trendAnalysis.name')}
          description={t('templates.trendAnalysis.description')}
          placeholder={t('input.placeholder.keyword') || 'Enter keyword...'}
          loading={loading === 'keyword-trend'}
          onGenerate={(keyword) =>
            generateReport('keyword-trend', keyword, reportAPI.getKeywordTrend)
          }
        />
        <GeneratorCard
          icon={REPORT_TYPES['journal-quality'].icon}
          iconColor={REPORT_TYPES['journal-quality'].color}
          title={t('templates.readingList.name')}
          description={t('templates.readingList.description')}
          placeholder={t('input.placeholder.journal') || 'Enter journal name...'}
          loading={loading === 'journal-quality'}
          onGenerate={(journalName) =>
            generateReport('journal-quality', journalName, reportAPI.getJournalQuality)
          }
        />
        <GeneratorCard
          icon={REPORT_TYPES['author-impact'].icon}
          iconColor={REPORT_TYPES['author-impact'].color}
          title={t('templates.authorImpact.name')}
          description={t('templates.authorImpact.description')}
          placeholder={t('input.placeholder.author') || 'Enter author name...'}
          loading={loading === 'author-impact'}
          onGenerate={(authorName) =>
            generateReport('author-impact', authorName, reportAPI.getAuthorImpact)
          }
        />
      </div>

      {/* RESULT PANEL — formatted report per type */}
      <AnimatePresence mode="wait">
        {result && result.type === 'keyword-trend' && (
          <KeywordTrendResult
            key={`kw-${result.timestamp}`}
            data={result.data}
            onClose={() => setResult(null)}
            onSave={handleSave}
            saving={saving}
          />
        )}
        {result && result.type === 'author-impact' && (
          <AuthorImpactResult
            key={`au-${result.timestamp}`}
            data={result.data}
            onClose={() => setResult(null)}
            onSave={handleSave}
            saving={saving}
          />
        )}
        {result && result.type === 'journal-quality' && (
          <JournalQualityResult
            key={`jn-${result.timestamp}`}
            data={result.data}
            onClose={() => setResult(null)}
            onSave={handleSave}
            saving={saving}
          />
        )}
      </AnimatePresence>

      {/* REPORT HISTORY */}
      <ReportHistoryTable
        history={history}
        onView={handleView}
        onDelete={handleDelete}
      />
    </div>
  );
}
